### ISSUE TITLE
Connect the bot to the Reddit API

### ISSUE THREAD

**Issue by PointBreak600** [PointBreak600/Aww-BOT#1]
Make a command that displays posts from r/aww in any order

**Comment by UncleWeeds** [comment]
@PointBreak600 Hey I am a Participant of DWOC, I would like to work on this issue

**Comment by PointBreak600** [comment]
> @PointBreak600 Hey I am a Participant of DWOC, I would like to work on this issue 

Sure! If you need any help let me know.

**Comment by UncleWeeds** [comment]
> > @PointBreak600 Hey I am a Participant of DWOC, I would like to work on this issue 
> 
> Sure! If you need any help let me know.

Cool, just assign me this issue and the other issue I messaged for
